/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexRowReduce.Nullspace
import all HexRowReduce.Nullspace

public section

/-!
Public `Matrix`-level wrappers backed by the executable `rowReduce`: the
row-span tests `spanCoeffs`/`spanContains`, the rank projection
`rowReduce_rank`, and the nullspace basis `nullspaceBasisMatrix`/`nullspace`.
-/

namespace Hex

universe u

namespace Matrix

variable {R : Type u} {n m : Nat}

/-- Convenience wrapper: compute row-span coefficients using `rowReduce` internally. -/
@[expose]
def spanCoeffs [Lean.Grind.Field R] [DecidableEq R] (M : Matrix R n m) (v : Vector R m) :
    Option (Vector R n) :=
  let E := (rowReduce_isRowReduced M).toIsEchelonForm
  E.spanCoeffs v

/-- Wrapper-layer soundness contract for `Matrix.spanCoeffs`. -/
@[grind =>]
theorem spanCoeffs_sound [Lean.Grind.Field R] [DecidableEq R]
    (M : Matrix R n m) (v : Vector R m) (c : Vector R n) :
    spanCoeffs M v = some c → vecMul c M = v := by
  intro h
  exact (rowReduce_isRowReduced M).toIsEchelonForm.spanCoeffs_sound v c h

/-- Convenience wrapper: decide row-span membership using `rowReduce` internally. -/
@[expose]
def spanContains [Lean.Grind.Field R] [DecidableEq R] (M : Matrix R n m) (v : Vector R m) :
    Bool :=
  let E := (rowReduce_isRowReduced M).toIsEchelonForm
  E.spanContains v

/-- The public `spanContains` wrapper is the Boolean `isSome` view of
`spanCoeffs`. -/
@[simp, grind =] theorem spanContains_eq_isSome [Lean.Grind.Field R] [DecidableEq R]
    (M : Matrix R n m) (v : Vector R m) :
    spanContains M v = (spanCoeffs M v).isSome := by
  rfl

/-- The public `spanContains` wrapper is exactly row-span membership. -/
@[grind =]
theorem spanContains_iff [Lean.Grind.Field R] [DecidableEq R]
    (M : Matrix R n m) (v : Vector R m) :
    spanContains M v = true ↔ ∃ c : Vector R n, vecMul c M = v := by
  unfold spanContains
  simpa using (rowReduce_isRowReduced M).spanContains_iff v

/-- `spanCoeffs` returns `none` exactly when `v` is in no row combination of `M`,
so a `none` result certifies that `v` is not in the row span. -/
@[grind =]
theorem spanCoeffs_eq_none_iff [Lean.Grind.Field R] [DecidableEq R]
    (M : Matrix R n m) (v : Vector R m) :
    spanCoeffs M v = none ↔ ¬ ∃ c : Vector R n, vecMul c M = v := by
  rw [← spanContains_iff, spanContains_eq_isSome]
  cases spanCoeffs M v <;> simp

/-- The rank returned by `rowReduce`. -/
@[expose]
def rowReduce_rank [Lean.Grind.Field R] [DecidableEq R] (M : Matrix R n m) : Nat :=
  (rowReduce M).rank

/-- The public nullspace basis assembled as a matrix of basis columns. -/
@[expose]
def nullspaceBasisMatrix [Lean.Grind.Field R] [DecidableEq R] (M : Matrix R n m) :
    Matrix R m (m - rowReduce_rank M) :=
  let E := rowReduce_isRowReduced M
  E.nullspaceMatrix

/-- Convenience wrapper: compute the nullspace basis using `rowReduce` internally. -/
@[expose]
def nullspace [Lean.Grind.Field R] [DecidableEq R] (M : Matrix R n m) :
    Vector (Vector R m) (m - rowReduce_rank M) :=
  let E := rowReduce_isRowReduced M
  E.nullspace

/-- Public column bridge between the matrix and vector nullspace wrappers:
the `k`-th column of `nullspaceBasisMatrix M` is the `k`-th vector in
`nullspace M`. -/
@[grind =>]
theorem nullspaceBasisMatrix_col [Lean.Grind.Field R] [DecidableEq R]
    (M : Matrix R n m) (k : Fin (m - rowReduce_rank M)) :
    Matrix.col (nullspaceBasisMatrix M) k = (nullspace M).get k := by
  unfold nullspaceBasisMatrix nullspace
  exact ((rowReduce_isRowReduced M).nullspace_get k).symm

/-- Every vector returned by the public `nullspace` wrapper is annihilated by `M`. -/
@[grind =>]
theorem nullspace_sound [Lean.Grind.Field R] [DecidableEq R] (M : Matrix R n m)
    (k : Fin (m - rowReduce_rank M)) :
    M * (nullspace M).get k = 0 := by
  unfold nullspace rowReduce_rank
  exact (rowReduce_isRowReduced M).nullspace_sound k

/-- Every vector annihilated by `M` is generated by the public nullspace basis matrix. -/
@[grind =>]
theorem nullspace_complete [Lean.Grind.Field R] [DecidableEq R] (M : Matrix R n m)
    (v : Vector R m) :
    M * v = 0 → ∃ c : Vector R (m - rowReduce_rank M), nullspaceBasisMatrix M * c = v := by
  intro hv
  unfold nullspaceBasisMatrix rowReduce_rank
  exact (rowReduce_isRowReduced M).nullspace_complete v hv



end Matrix
end Hex
